# ==========================================
# SomnGuard - Liquibase Configuration
# ==========================================

driver=org.postgresql.Driver

changeLogFile=changelog/changelog-master.yaml

searchPath=/workspace

defaultSchemaName=public
liquibaseSchemaName=public