DROP INDEX IF EXISTS device_management.ix_device_assignment_device_id;
DROP INDEX IF EXISTS device_management.ix_device_assignment_user_id;
DROP INDEX IF EXISTS device_management.ix_device_config_device_id;
DROP INDEX IF EXISTS device_management.ix_device_serial_number;