DROP INDEX IF EXISTS telemetry_service.ix_event_device_id;
DROP INDEX IF EXISTS telemetry_service.ix_event_event_type_id;
DROP INDEX IF EXISTS telemetry_service.ix_evidence_event_id;
DROP INDEX IF EXISTS telemetry_service.ix_evidence_media_type_id;
DROP INDEX IF EXISTS telemetry_service.ix_alert_log_event_id;
DROP INDEX IF EXISTS telemetry_service.ix_alert_log_sound_pattern_id;
DROP INDEX IF EXISTS telemetry_service.ix_alert_log_severity_id;
DROP INDEX IF EXISTS telemetry_service.ix_event_occurred_at;
DROP INDEX IF EXISTS telemetry_service.ix_alert_log_triggered_at;